version: "3.9"
services:
  admin:
    build:
      context: .
      dockerfile: ./admin/Dockerfile
      args:
        APP_PORT: "5001"
        APP_NODE_ENV: "development"
    ports:
      - "5001:5001"
    volumes:
      - ./admin:/github.com/dark-vinci/node-fullstack/jumian/client/admin
      - /github.com/dark-vinci/node-fullstack/jumian/client/admin/node_modules
    tty: true
    stdin_open: true
    command: npm start

  application:
    build:
      context: .
      dockerfile: ./application/Dockerfile
      args:
        APP_PORT: "6001"
        APP_NODE_ENV: "development"
    ports:
      - "6001:6001"
    volumes:
      - ./admin:/github.com/dark-vinci/node-fullstack/jumian/client/application
      - /github.com/dark-vinci/node-fullstack/jumian/client/application/node_modules
    tty: true
    stdin_open: true
    command: npm start
